Repository Gamegoo-repo/Gamegoo-socket-server, pull requests merged in 2024-09, with the labels that each got.

#64 [Feat/63] matching_not_found 로직 추가
  public/matching/scripts/socket.js
  socket/handlers/matching/matchingHandler/matchingFoundHandler.js
  socket/handlers/matching/matchingSocketListeners.js
Labels: :sparkles: feature

#66 ✨ [Feat] matching_retry 구현
  socket/handlers/matching/matchingSocketListeners.js
Labels: :sparkles: feature

#68 [Feat/67] 매칭 실패 로직
  public/matching/scripts/socket.js
  socket/emitters/matchingEmitter.js
  socket/handlers/matching/matchingSocketListeners.js
Labels: :sparkles: feature

#72 [Fix/71] 친구 목록 조회 API 변경에 따른 소켓 초기화 로직 수정
  app/app.js
  public/scripts/api.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  public/styles.css
  socket/apis/friendApi.js
  socket/handlers/friend/friendInitializer.js
  socket/socket.js
Labels: :bug: bug, :sparkles: feature

#74 🐛 [Fix] 채팅방 새로 생성 시 채팅방 영역 렌더링 안되는 버그 수정
  public/scripts/eventListeners.js
Labels: :bug: bug

#70 [Fix/69] 매칭 관련 수정
  public/matching/scripts/socket.js
  socket/apis/matchApi.js
  socket/emitters/matchingEmitter.js
  socket/handlers/matching/matchingHandler/matchingFoundHandler.js
  socket/handlers/matching/matchingSocketListeners.js
Labels: :bug: bug

#77 [Feat/76] 시스템 메시지 전송 event emit API 구현
  app/controller/socketController.js
  app/routers/index.js
  socket/emitters/chatEmitter.js
Labels: :sparkles: feature

#85 ♻️ [Refactor] manner-system-message 이벤트 분리
  app/controller/socketController.js
  public/scripts/socket.js
  socket/emitters/chatEmitter.js
Labels: ♻️ refactor

#87 [Feat/86] 테스트 수정 사항 반영 PR
  public/matching/scripts/socket.js
Labels: :bug: bug

#88 [Fix/78] 채팅방 목록 조회 API 변경에 따른 프론트 코드 수정
  public/scripts/api.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  public/styles.css
Labels: :bug: bug

#89 [Feat/84] 시스템 메세지 구현
  app/controller/systemMessageController.js
  app/routers/index.js
  socket/handlers/matching/matchingSocketListeners.js
  socket/socket.js
Labels: :bug: bug, :sparkles: feature

#91 [Feat/90] 프론트 도메인 CORS 허용
  app/app.js
  index.js
  socket/socket.js
Labels: :sparkles: feature
