Repository Gamegoo-repo/Gamegoo-socket-server, pull requests merged in 2024-10, with the labels that each got.

#95 [Refactor/93] winston 모듈 설정
  common/winston.js
  package-lock.json
  package.json
Labels: ♻️ refactor

#97 [Refactor/96] winston 모듈 logger를 이용한 로그 출력
  app/controller/loginController.js
  index.js
  socket/apis/chatApi.js
  socket/apis/friendApi.js
  socket/apis/matchApi.js
  socket/common/memberSocketMapper.js
  socket/emitters/errorEmitter.js
  socket/emitters/friendEmitter.js
  socket/emitters/matchingEmitter.js
  socket/emitters/memberEmitter.js
  socket/events/eventBus.js
  socket/events/handlers/matchingHandler.js
  socket/events/matchingEventsListener.js
  socket/handlers/chat/chatInitializer.js
  socket/handlers/friend/friendInitializer.js
  socket/handlers/matching/matchingHandler/matchingCommonHandler.js
  socket/handlers/matching/matchingHandler/matchingFoundHandler.js
  socket/handlers/matching/matchingHandler/matchingStartedHandler.js
  socket/handlers/matching/matchingSocketListeners.js
  socket/socket.js
Labels: ♻️ refactor

#102 [Fix/10] matching-found-sender emit 시 딜레이 주기
  socket/handlers/matching/matchingSocketListeners.js
Labels: :bug: bug

#103 🐛[fix] 게임 스타일 에러 해결
  socket/apis/matchApi.js
Labels: :bug: bug

#104 [FIx/101] matching-found-sender emit 시 2초 딜레이 rollback
  socket/handlers/matching/matchingSocketListeners.js
Labels: :bug: bug

#106 [Feat/105] manner-system-message에 timestamp 추가
  app/controller/socketController.js
  socket/emitters/chatEmitter.js
Labels: :sparkles: feature

#107 [Fix/94] jwt 토큰 만료 에러 수정
  public/scripts/api.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  socket/emitters/errorEmitter.js
  socket/handlers/chat/chatInitializer.js
  socket/handlers/friend/friendInitializer.js
  socket/handlers/matching/matchingHandler/matchingStartedHandler.js
  socket/socket.js
Labels: ♻️ refactor, :bug: bug, :sparkles: feature

#109 [Fix/108] 3000->8080서버 요청 시 internal API 사용하도록 변경
  socket/apis/chatApi.js
  socket/apis/friendApi.js
  socket/apis/matchApi.js
Labels: :bug: bug
