Repository Gamegoo-repo/Gamegoo-socket-server, pull requests merged in 2024-08, with the labels that each got.

#27 [Feat/26] 채팅방 목록 조회 및 채팅방 입장 기능 구현
  public/scripts/api.js
  public/scripts/eventListeners.js
Labels: :sparkles: feature

#29 [Feat/28] 채팅 메시지 전송 및 메시지 받기 기능 구현
  public/scripts/api.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  socket/apis/chatApi.js
  socket/emitters/chatEmitter.js
  socket/handlers/chat/chatHandler.js
Labels: :sparkles: feature

#31 [Feat/30] 메시지 내역 조회 api 요청 및 렌더링
  public/scripts/api.js
  public/scripts/eventListeners.js
Labels: :sparkles: feature

#32 [Feat/30] flow 주석 수정 및 에러처리 리팩토링
  public/scripts/eventListeners.js
  socket/apis/chatApi.js
  socket/apis/friendApi.js
  socket/handlers/chat/chatHandler.js
  socket/socket.js
Labels: ♻️ refactor, :memo: documentation

#34 [Feat/33] 채팅방 나가기, 시작하기 기능 구현 및 버그 수정
  app/app.js
  public/scripts/api.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  socket/apis/friendApi.js
Labels: ♻️ refactor, :bug: bug, :sparkles: feature

#36 [Feat/35] 알림 버튼 추가 및 알림창 화면 구현
  app/app.js
  public/scripts/eventListeners.js
  public/styles.css
Labels: :sparkles: feature

#38 [Feat/37] 알림창 및 채팅방 내부 메뉴 화면 구현
  app/app.js
  public/scripts/eventListeners.js
  public/styles.css
Labels: ♻️ refactor, :sparkles: feature

#40 [Feat/39] 채팅방 API 변경 반영 및 친구목록, 채팅방 입장/시작 관련 로직 추가
  public/scripts/api.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  public/styles.css
Labels: ♻️ refactor, :sparkles: feature

#44 [Feat/43] 채팅방 room join API 및 room leave 구현
  app/controller/socketController.js
  app/routers/index.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  socket/emitters/chatEmitter.js
  socket/handlers/chat/chatHandler.js
Labels: :sparkles: feature

#46 [Refactor/45] 기존 코드 리팩토링 및 주석 추가
  app/controller/loginController.js
  app/controller/socketController.js
  app/routers/index.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  socket/handlers/chat/chatHandler.js
  socket/handlers/chat/chatInitializer.js
  socket/handlers/friend/friendInitializer.js
Labels: ♻️ refactor, :memo: documentation

#48 [Feat/47] 채팅 시스템 메시지 기능 구현
  app/app.js
  public/scripts/api.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  public/styles.css
  socket/apis/chatApi.js
  socket/common/memberSocketMapper.js
  socket/emitters/chatEmitter.js
  socket/handlers/chat/chatHandler.js
Labels: ♻️ refactor, :bug: bug, :sparkles: feature

#49 [Feat/17] 매칭에 사용자가 들어올 경우 소켓, 프론트 작업
  app/app.js
  public/matching/scripts/api.js
  public/matching/scripts/eventListeners.js
  public/matching/scripts/socket.js
  public/matching/style.css
  public/styles.css
  socket/handlers/matching/matchingHandler.js
  socket/handlers/matching/matchingInit.js
  socket/handlers/matching/matchingInitializer.js
Labels: :sparkles: feature

#51 [Docs/50] Flow별 주석 추가 및 수정
  app/controller/socketController.js
  app/routers/index.js
  public/scripts/eventListeners.js
  public/scripts/socket.js
  socket/handlers/chat/chatHandler.js
Labels: :memo: documentation

#53 [Feat/52] 우선순위 값 소켓에 넣기
  package-lock.json
  package.json
  socket/apis/matchApi.js
  socket/handlers/matching/matchingHandler.js
  socket/handlers/matching/matchingInitializer.js
Labels: :sparkles: feature

#55 [Feat/54] Matching Found Emit 기능 구현
  socket/apis/matchApi.js
  socket/common/PriorityTree.js
  socket/handlers/matching/matchingHandler.js
  socket/handlers/matching/matchingHandler/matchingStartedHandler.js
  socket/handlers/matching/matchingInit.js
  socket/handlers/matching/matchingInitializer.js
  socket/handlers/matching/matchingListeners.js
Labels: ♻️ refactor, :sparkles: feature

#58 [Refactor/57] 매칭 상태 수정 API 변경 반영
  socket/apis/matchApi.js
  socket/common/memberSocketMapper.js
  socket/handlers/matching/matchingHandler/matchingStartedHandler.js
  socket/handlers/matching/matchingListeners.js
Labels: ♻️ refactor

#60 [Refactor/59] events 모듈 도입 및 listener 설정
  index.js
  socket/events/eventBus.js
  socket/events/handlers/matchingHandler.js
  socket/events/matchingEventsListener.js
  socket/handlers/matching/matchingHandler/matchingStartedHandler.js
  socket/handlers/matching/matchingInit.js
  socket/handlers/matching/matchingInitializer.js
  socket/handlers/matching/matchingSocketListeners.js
Labels: ♻️ refactor

#62 [Feat/61] 매칭 성공 flow #20 구현
  app/app.js
  public/img/heart.png
  public/img/profile_1.png
  public/img/profile_3.png
  public/matching/scripts/eventListeners.js
  public/matching/scripts/socket.js
  public/matching/style.css
  public/matching/styles.css
  public/scripts/eventListeners.js
  public/scripts/socket.js
  socket/apis/matchApi.js
  socket/emitters/matchingEmitter.js
  socket/handlers/matching/matchingHandler/matchingCommonHandler.js
  socket/handlers/matching/matchingHandler/matchingFoundHandler.js
  socket/handlers/matching/matchingHandler/matchingStartedHandler.js
  socket/handlers/matching/matchingSocketListeners.js
Labels: :sparkles: feature
