Repository Gamegoo-repo/Gamegoo-socket-server, pull requests merged in 2025-08, with the labels that each got.

#146 [Ci/145] 운영/개발/QA 환경 분리
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-qa.yml
  Dockerfile-dev
  Dockerfile-prod
  Dockerfile-qa
  app/app.js
  common/winston.js
  index.js
  socket/socket.js
Labels: :construction_worker: ci

#150 [Feat/149] 친구 온라인 이벤트 API 구현
  app/controller/FriendOnlineController.js
  app/routers/index.js
Labels: :sparkles: feature

#152 [Fix/151] 매칭 오브젝트 초기화 수정
  socket/handlers/matching/matchingHandler/matchingFailHandler.js
  socket/handlers/matching/matchingHandler/matchingManager.js
Labels: :bug: bug
